version: '4.3'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.in
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - '6300:8080'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
