services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.in
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - '6300:8080'
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todos
      JWT_SECRET: myjwtsecret
    ports:
      - '8080:8080'
    depends_on:
      - db
